apiVersion: v1
kind: Service
metadata:
  name: geoengine
  labels:
    app: geoengine
spec:
  selector:
    app: geoengine
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP
# config-rev: 1
# config-rev: 2
