#!/bin/sh

set -e

cd $(dirname $0)
export CommandsJSON="$(cat commands.json)"

# replace out the json [r1] [r2] [r3] [r4]
perl -pe '
    while (($i = index($_, "{{.CommandsJSON}}")) != -1) {
      substr($_, $i, length("{{.CommandsJSON}}")) = $ENV{"CommandsJSON"};
    }
' commands.go > commands_gen.go

# remove the ignore
sed -i -e 's/\/\/go:build ignore/\/\/ This file was autogenerated. DO NOT EDIT./g' commands_gen.go
rm -rf commands_gen.go-e
# script-rev: 5
# rev: 1
# rev: 2
